### PR TITLE
adds gulp-plumber to all tasks, restarting them on error

### PR DESCRIPTION
**Pull request by tonekk**

### CODE REVIEW

**Comment by zcei** [comment]
I'm heavily against monkey-patching `gulp.src` with an `emit('end')` in the error handler.

This basically prevents using gulp for non-`watch` tasks, as the exit code will always be `0`.
e.g. TravisCI can't be used to test / deploy, as it would always notify a success.

**Comment by tonekk** [comment]
But we won't have tests in a static site generator I guess.

Anyway, what would you suggest?
Something like:

``` js
gulp.plumberSrc = function() { ... };
```

**Comment by axe312ger** [comment]
I am also not a fan of this plumber monkey patching. But looks like some gulp plugins do not emit errors correctly so its hardly needed some times. Any thoughts?

**Comment by tonekk** [comment]
`Hardly needed` is right here.
It's a mess to work with it like this, because it will crash anytime you have a jade / sass error, forcing you to restart the server, which will then reopen the browser tab -> **maximum annoyance**

**Comment by tonekk** [comment]
appropriate? @zcei @axe312ger

**Comment by zcei** [comment]
To keep `gulp`s API untouched, I would use smth. like this:

``` js
function swallowError() {
  return plumber({
    errorHandler: function (err) {
      console.log(err);
      this.emit('end');
    }
  });
}

// ...

gulp.task('jade', function() {
  return gulp.src('./assets/jade/**/*.jade')
    .pipe(swallowError())
    .pipe(jade({
      pretty: true
    }))
    .pipe(gulp.dest('./dist'));
});
```

Tho, it's more a question of taste, guess I'm too heavily into `immutable` (_functional_) coding style.
I'd let @axe312ger decide.

**Comment by zcei** [comment]
And btw., we can still catch `error` events from the failing task itself, or was that what you meant @axe312ger?

General intention from my side: don't let each and every error go through, but better announce it somehow.
e.g. we could add the gulp notifications and announce the failing task to us for dev purposes and still throw proper exit codes at deployment. (We may not need CI, but CD would also let everything through)

One minor thing: `console.log` could be replaced by `gutil.log`, to everything looks fancy with times, colors, etc.

**Comment by zcei** [comment]
Even this should work:

``` js
function swallowError() {
  console.log(err);
  this.emit('end');
}

// ...

gulp.task('jade', function() {
  return gulp.src('./assets/jade/**/*.jade')
    .pipe(plumber(swallowError))
    .pipe(jade({
      pretty: true
    }))
    .pipe(gulp.dest('./dist'));
});
```

**Comment by tonekk** [comment]
Dajum

**Comment by zcei** [comment]
My fault, should have been more concise here: `gulp-util`, wasn't aware that there is a `gutil` package :see_no_evil: (both can be used as `devDependency`, right? ;)) 

fyi: `plumber(handler)` defaults to `plumber({ errorHandler: handler })`

**Comment by tonekk** [comment]
Was wondering why the output is the same as `console.log` :stuck_out_tongue_closed_eyes:

**Comment by zcei** [comment]
Wonderful! 
@axe312ger :ship: ?

**Comment by axe312ger** [comment]
I'll have a look on this later, since its to much to review without testing -> still in the office :office:

**Comment by axe312ger** [comment]
I had time to look at it and I prefer to do it without :monkey_face: patching. Also notifications would be nice, right?
We might use some code from the wk repos I created the last days:
https://github.com/wunderkraut/gulp-task-postcss/blob/master/index.js#L47
https://github.com/wunderkraut/gulp-task-postcss/blob/master/index.js#L87

**Comment by zcei** [comment]
Out of scope for this PR, if you ask me.

**Comment by axe312ger** [comment]
True, so lets split it up. Just got no time for it yet. Maybe @tonekk wanna contribute? :)

**Pull request closed without merging**
