### PR TITLE
fixes opening of index.html

### PR DESCRIPTION
**Pull request by tonekk**

### CODE REVIEW

**Comment by yannickoo** [comment]
:ship:

**Comment by zcei** [comment]
How about using `node-open` here, the underlaying lib of `gulp-open`?
Simply call `open('http://localhost:3001')` from within `server.start` callback.

**Comment by axe312ger** [comment]
:+1:

**Comment by tonekk** [comment]
done

**Comment by axe312ger** [comment]
Thx. Looks good. Also for that .gitignore typo.

**Comment by zcei** [comment]
:ok_hand:

**Pull request merged**
